[project]
name = "nft-fractionalizer"
authors = ["Erfan Yeganegi <yeganegierfan@gmail.com>"]
description = "DROPLinked NFT Fractionalizer"
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.sft-trait]
path = "contracts/traits/sft-trait.clar"

[contracts.ft-trait]
path = "contracts/traits/ft-trait.clar"

[contracts.nft-fractionalizer]
path = "contracts/nft-fractionalizer.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
